[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.dev]
[context.dev.environment]
  VUE_APP_PAYSTACK_KEY="pk_test_c8e98d4f4824f71baf1e879f49e666487e526a85"

[context.production]
[context.dev.production]
  VUE_APP_PAYSTACK_KEY="pk_test_c8e98d4f4824f71baf1e879f49e666487e526a85"